### ISSUE TITLE
Example code throws: AttributeError: 'FigureCanvasTkAgg' object has no attribute 'show'

### ISSUE THREAD

**Issue by mfisher-klarisdx** [ceyzeriat/joystick#6]
python: 3.5.2
joystick: 0.3.8
tkinter: 8.6  ("python3 -m tkinter" reports 8.6)

When running the example code from: https://pypi.org/project/joystick/, I get the following exception and traceback:

Traceback (most recent call last):
  File "jtest.py", line 71, in <module>
    t = test()
  File "/home/mfisher/.local/lib/python3.5/site-packages/joystick/joystick.py", line 49, in __init__
    self._callmthd(after, **kwargs)
  File "/home/mfisher/.local/lib/python3.5/site-packages/joystick/core.py", line 177, in callmthd
    ret.append(getattr(obj, item)(**kwargs))
  File "/home/mfisher/.local/lib/python3.5/site-packages/joystick/deco.py", line 156, in func_wrapper
    func(self, **kwargs)  # finally calling some stuff
  File "jtest.py", line 27, in _build_frames
    xylim=(0,10,0,1), xlabel='t', ylabel='random'))
  File "/home/mfisher/.local/lib/python3.5/site-packages/joystick/graph.py", line 105, in __init__
    self._init_base(**self._kwargs)
  File "/home/mfisher/.local/lib/python3.5/site-packages/joystick/graph.py", line 113, in _init_base
    self._init_basic_graph(**kwargs)
  File "/home/mfisher/.local/lib/python3.5/site-packages/joystick/graph.py", line 130, in _init_basic_graph
    self._canvas.show()
AttributeError: 'FigureCanvasTkAgg' object has no attribute 'show'

**Comment by sakshatshinde** [comment]
@mfisher-klarisdx this should be using the draw() instead of show()

**Comment by Alex031544** [comment]
https://github.com/jarvisteach/appJar/issues/551
